### ISSUE TITLE
on item hover problem

### ISSUE THREAD

**Issue by AmirDoosti** [UnTalPeluca/kanban-task-management#2]
when we drag an item , it keeps a duplicate of it in it's original place.
and it wont allow us to drop it back where it was, so we have to drop it some place else.
thank you for you great work, i used your kanban board and its works well but this issue remains.

**Comment by UnTalPeluca** [comment]
Hi Amir! Yes, I'm aware of that error. I wrote the drag and drop code quickly, as there are many things in the code that I wrote quickly since a project like this requires a lot of time. Anyway, I'm glad it's helpful to you! I'll try to fix it soon.

**Comment by UnTalPeluca** [comment]
I solved it! I hope everything works as it should

**Comment by AmirDoosti** [comment]
hi there rodrigo, thank you for your reply. actually i fixed it in my own way but thank you for fixing it as well.
here is what is added to you code: 
1. i added "drag" event to "BoardTask" component 
2. defined positions for starting second, and when its still being dragged.
3. changed "dragStart" event which you had been written 
4. wrote "drag" event
``` js
// 1
 drag="OnDrag($event, task.id)"

// 2
let old_topPosition = null;
let old_bottomPosition = null;
let old_leftPosition = null;
let old_rightPosition = null;

let current_topPosition = null;
let current_bottomPosition = null;
let current_leftPosition = null;
let current_rightPosition = null;

// 3
const onDragTask = (evt, task, columnIndex, taskIndex) => {
  managerStore.dragging = true
  draggedTask.value = {
    el: evt.target,
    task,
    columnIndex,
    taskIndex
  }
  old_topPosition = Math.floor(draggedTask.value.el.getBoundingClientRect().top);
  old_rightPosition = Math.floor(draggedTask.value.el.getBoundingClientRect().right);
  old_bottomPosition = Math.floor(draggedTask.value.el.getBoundingClientRect().bottom);
  old_leftPosition = Math.floor(draggedTask.value.el.getBoundingClientRect().left);
}
// 4
const OnDrag = (evt)=> {
  // Get the current position of the element
  current_topPosition = evt.clientY;
  current_leftPosition = evt.clientX;
  current_rightPosition = evt.clientX + evt.clientWidth;
  current_bottomPosition = evt.clientY + evt.clientHeight;

  if (current_leftPosition > old_leftPosition && current_leftPosition < old_rightPosition && current_topPosition > old_topPosition && current_topPosition < old_bottomPosition) {
    removeTempTask()
  }
}
```

i dont know if i did it in the best way possible , but i worked for me.
